# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-31 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='credentials',
            fields=[
                ('user_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('password', models.CharField(default='', max_length=200)),
                ('client_id', models.CharField(default='', max_length=200)),
                ('client_secret', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='scopes',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('value', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='secrets',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('client_id', models.TextField(default='')),
                ('client_secret', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='tokens',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('access_token', models.TextField(default='')),
                ('refresh_token', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='urls',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('value', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
